-- Distribución completa (no voto mayoritario único) de redes de
-- Cole-Anticevic sobre el cerebelo (ambos hemisferios). Generado por
-- scripts/register_cerebellum_network_distribution.py. Ver decisión
-- del 29/08/2026 en docs/analisis-arquitectura.md.

INSERT INTO region_network_memberships (id, region_id, network_id, confidence, method, source_dataset_id, algorithm, created_at) VALUES
  ('membership.human.cole-anticevic.l_cerebellum__frontoparietal', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.frontoparietal', 0.29842691468595706, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__dorsal-attention', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.dorsal-attention', 0.15087840165346195, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__cingulo-opercular', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.cingulo-opercular', 0.1482374555057986, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__somatomotor', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.somatomotor', 0.14100355953611207, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__default', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.default', 0.12056493282810886, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__visual2', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.visual2', 0.06097140888735791, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__posterior-multimodal', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.posterior-multimodal', 0.043288552072568605, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__visual', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.visual', 0.03318406246411758, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__language', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.language', 0.0028705936387644964, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.l_cerebellum__auditory', 'region.human.hcp-subcortex.l_cerebellum', 'network.human.cole-anticevic.auditory', 0.0005741187277528993, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__frontoparietal', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.frontoparietal', 0.26060804899387574, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__default', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.default', 0.17300962379702536, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__dorsal-attention', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.dorsal-attention', 0.15955818022747156, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__somatomotor', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.somatomotor', 0.1399825021872266, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__cingulo-opercular', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.cingulo-opercular', 0.11482939632545931, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__visual', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.visual', 0.048118985126859144, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__visual2', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.visual2', 0.04319772528433946, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__language', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.language', 0.03346456692913386, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__posterior-multimodal', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.posterior-multimodal', 0.02701224846894138, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now()),
  ('membership.human.cole-anticevic.r_cerebellum__auditory', 'region.human.hcp-subcortex.r_cerebellum', 'network.human.cole-anticevic.auditory', 0.00021872265966754156, 'distribucion_completa_de_grayordinates_sobre_la_particion_cole_anticevic_wsubcorgsr_netassignments_lr_excluyendo_fondo_sin_voto_mayoritario_unico_estructura_funcionalmente_distribuida', 'dataset.human.hcp.s1200_groupavg_extracted', 'full_distribution', now())
ON CONFLICT (id) DO UPDATE SET confidence = EXCLUDED.confidence, method = EXCLUDED.method;
