-- Backfill de authors/journal/abstract para el Study de Zhang et al. 2018.
-- Generado por scripts/backfill_zhang2018_study_metadata.py.

INSERT INTO studies (id, name, doi, year, authors, journal, abstract) VALUES (
  'study.human.zhang2018.zhang_2018', 'Zhang F, Wu Y, Norton I, Rigolo L, Rathi Y, Makris N, O''Donnell LJ (2018). An anatomically curated fiber clustering white matter atlas for consistent white matter tract parcellation across the lifespan. NeuroImage, 179, 429-447.', '10.1016/j.neuroimage.2018.06.027', 2018,
  ARRAY['Fan Zhang', 'Ye Wu', 'Isaiah Norton', 'Laura Rigolo', 'Yogesh Rathi', 'Nikos Makris', 'Lauren J. O''Donnell'], 'NeuroImage', 'This work presents an anatomically curated white matter atlas to enable consistent white matter tract parcellation across different populations. Leveraging a well-established computational pipeline for fiber clustering, we create a tract-based white matter atlas including information from 100 subjects. A novel anatomical annotation method is proposed that leverages population-based brain anatomical information and expert neuroanatomical knowledge to annotate and categorize the fiber clusters. A total of 256 white matter structures are annotated in the proposed atlas, which provides one of the most comprehensive tract-based white matter atlases covering the entire brain to date. These structures are composed of 58 deep white matter tracts including major long range association and projection tracts, commissural tracts, and tracts related to the brainstem and cerebellar connections, plus 198 short and medium range superficial fiber clusters organized into 16 categories according to the brain lobes they connect. Potential false positive connections are annotated in the atlas to enable their exclusion from analysis or visualization. In addition, the proposed atlas allows for a whole brain white matter parcellation into 800 fiber clusters to enable whole brain connectivity analyses. The atlas and related computational tools are open-source and publicly available. We evaluate the proposed atlas using a testing dataset of 584 diffusion MRI scans from multiple independently acquired populations, across genders, the lifespan (1 day to 82 years), and different health conditions (healthy control, neuropsychiatric disorders, and brain tumor patients). Experimental results show successful white matter parcellation across subjects from different populations acquired on multiple scanners, irrespective of age, gender or disease indications. Over 99% of the fiber tracts annotated in the atlas were detected in all subjects on average. One advantage in terms of robustness is that the tract-based pipeline does not require any cortical or subcortical segmentations, which can have limited success in young children and patients with brain tumors or other structural lesions. We believe this is the first demonstration of consistent automated white matter tract parcellation across the full lifespan from birth to advanced age.'
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  doi = EXCLUDED.doi,
  year = EXCLUDED.year,
  authors = EXCLUDED.authors,
  journal = EXCLUDED.journal,
  abstract = EXCLUDED.abstract;

