-- Backfill de regions.name para 360 regiones de HCP-MMP1.0.
-- Generado por scripts/backfill_hcp_mmp1_region_names.py.
-- Nombres verificados en backend/ingestion/neuroimaging/hcp_mmp1.py::REGION_LONG_NAMES (decisión 51, docs/analisis-arquitectura.md).

UPDATE regions SET name = 'Area 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_1';
UPDATE regions SET name = 'Area 10d (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_10d';
UPDATE regions SET name = 'Polar 10p (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_10pp';
UPDATE regions SET name = 'Area 10r (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_10r';
UPDATE regions SET name = 'Area 10v (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_10v';
UPDATE regions SET name = 'Area 11l (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_11l';
UPDATE regions SET name = 'Area 13l (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_13l';
UPDATE regions SET name = 'Area 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_2';
UPDATE regions SET name = 'Area 23c (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_23c';
UPDATE regions SET name = 'Area 23d (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_23d';
UPDATE regions SET name = 'Dorsal Area 24d (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_24dd';
UPDATE regions SET name = 'Ventral Area 24d (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_24dv';
UPDATE regions SET name = 'Area 25 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_25';
UPDATE regions SET name = 'Area 31a (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_31a';
UPDATE regions SET name = 'Area 31pd (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_31pd';
UPDATE regions SET name = 'Area 31p ventral (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_31pv';
UPDATE regions SET name = 'Area 33 prime (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_33pr';
UPDATE regions SET name = 'Area 3a (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_3a';
UPDATE regions SET name = 'Primary Sensory Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_3b';
UPDATE regions SET name = 'Primary Motor Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_4';
UPDATE regions SET name = 'Area 43 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_43';
UPDATE regions SET name = 'Area 44 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_44';
UPDATE regions SET name = 'Area 45 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_45';
UPDATE regions SET name = 'Area 46 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_46';
UPDATE regions SET name = 'Area 47l (47 lateral) (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_47l';
UPDATE regions SET name = 'Area 47m (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_47m';
UPDATE regions SET name = 'Area 47s (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_47s';
UPDATE regions SET name = 'Area 52 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_52';
UPDATE regions SET name = 'Area 55b (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_55b';
UPDATE regions SET name = 'Area 5L (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_5l';
UPDATE regions SET name = 'Area 5m (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_5m';
UPDATE regions SET name = 'Area 5m ventral (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_5mv';
UPDATE regions SET name = 'Area 6 anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_6a';
UPDATE regions SET name = 'Dorsal area 6 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_6d';
UPDATE regions SET name = 'Area 6m anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_6ma';
UPDATE regions SET name = 'Area 6mp (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_6mp';
UPDATE regions SET name = 'Rostral Area 6 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_6r';
UPDATE regions SET name = 'Ventral Area 6 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_6v';
UPDATE regions SET name = 'Lateral Area 7A (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_7al';
UPDATE regions SET name = 'Medial Area 7A (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_7am';
UPDATE regions SET name = 'Area 7m (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_7m';
UPDATE regions SET name = 'Area 7PC (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_7pc';
UPDATE regions SET name = 'Lateral Area 7P (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_7pl';
UPDATE regions SET name = 'Medial Area 7P (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_7pm';
UPDATE regions SET name = 'Area 8Ad (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_8ad';
UPDATE regions SET name = 'Area 8Av (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_8av';
UPDATE regions SET name = 'Area 8B Lateral (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_8bl';
UPDATE regions SET name = 'Area 8BM (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_8bm';
UPDATE regions SET name = 'Area 8C (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_8c';
UPDATE regions SET name = 'Area 9-46d (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_9-46d';
UPDATE regions SET name = 'Area 9 anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_9a';
UPDATE regions SET name = 'Area 9 Middle (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_9m';
UPDATE regions SET name = 'Area 9 Posterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_9p';
UPDATE regions SET name = 'Primary Auditory Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a1';
UPDATE regions SET name = 'Area anterior 10p (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a10p';
UPDATE regions SET name = 'Area a24 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a24';
UPDATE regions SET name = 'Anterior 24 prime (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a24pr';
UPDATE regions SET name = 'Area anterior 32 prime (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a32pr';
UPDATE regions SET name = 'Auditory 4 Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a4';
UPDATE regions SET name = 'Area anterior 47r (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a47r';
UPDATE regions SET name = 'Auditory 5 Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a5';
UPDATE regions SET name = 'Area anterior 9-46v (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_a9-46v';
UPDATE regions SET name = 'Anterior Agranular Insula Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_aaic';
UPDATE regions SET name = 'Anterior IntraParietal Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_aip';
UPDATE regions SET name = 'Anterior Ventral Insular Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_avi';
UPDATE regions SET name = 'Area dorsal 23 a+b (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_d23ab';
UPDATE regions SET name = 'Area dorsal 32 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_d32';
UPDATE regions SET name = 'Dorsal Transitional Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_dvt';
UPDATE regions SET name = 'Entorhinal Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ec';
UPDATE regions SET name = 'Frontal Eye Fields (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fef';
UPDATE regions SET name = 'Fusiform Face Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ffc';
UPDATE regions SET name = 'Frontal Opercular Area 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fop1';
UPDATE regions SET name = 'Frontal Opercular Area 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fop2';
UPDATE regions SET name = 'Frontal Opercular Area 3 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fop3';
UPDATE regions SET name = 'Frontal Opercular Area 4 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fop4';
UPDATE regions SET name = 'Area Frontal Opercular 5 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fop5';
UPDATE regions SET name = 'Area FST (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_fst';
UPDATE regions SET name = 'Hippocampus (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_h';
UPDATE regions SET name = 'Inferior 6-8 Transitional Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_i6-8';
UPDATE regions SET name = 'Area IFJa (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ifja';
UPDATE regions SET name = 'Area IFJp (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ifjp';
UPDATE regions SET name = 'Area IFSa (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ifsa';
UPDATE regions SET name = 'Area IFSp (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ifsp';
UPDATE regions SET name = 'Insular Granular Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ig';
UPDATE regions SET name = 'Area IntraParietal 0 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ip0';
UPDATE regions SET name = 'Area IntraParietal 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ip1';
UPDATE regions SET name = 'Area IntraParietal 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ip2';
UPDATE regions SET name = 'IntraParietal Sulcus Area 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ips1';
UPDATE regions SET name = 'Lateral Belt Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_lbelt';
UPDATE regions SET name = 'Area Lateral IntraParietal dorsal (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_lipd';
UPDATE regions SET name = 'Area Lateral IntraParietal ventral (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_lipv';
UPDATE regions SET name = 'Area Lateral Occipital 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_lo1';
UPDATE regions SET name = 'Area Lateral Occipital 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_lo2';
UPDATE regions SET name = 'Area Lateral Occipital 3 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_lo3';
UPDATE regions SET name = 'Medial Belt Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_mbelt';
UPDATE regions SET name = 'Middle Insular Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_mi';
UPDATE regions SET name = 'Medial IntraParietal Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_mip';
UPDATE regions SET name = 'Medial Superior Temporal Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_mst';
UPDATE regions SET name = 'Middle Temporal Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_mt';
UPDATE regions SET name = 'Orbital Frontal Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ofc';
UPDATE regions SET name = 'Area OP1-SII (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_op1';
UPDATE regions SET name = 'Area OP2-3-VS (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_op2-3';
UPDATE regions SET name = 'Area OP4-PV (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_op4';
UPDATE regions SET name = 'Area posterior 10p (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p10p';
UPDATE regions SET name = 'Area posterior 24 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p24';
UPDATE regions SET name = 'Area Posterior 24 prime (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p24pr';
UPDATE regions SET name = 'Area p32 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p32';
UPDATE regions SET name = 'Area p32 prime (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p32pr';
UPDATE regions SET name = 'Area posterior 47r (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p47r';
UPDATE regions SET name = 'Area posterior 9-46v (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_p9-46v';
UPDATE regions SET name = 'ParaBelt Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pbelt';
UPDATE regions SET name = 'PreCuneus Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pcv';
UPDATE regions SET name = 'Perirhinal Ectorhinal Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_peec';
UPDATE regions SET name = 'Premotor Eye Field (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pef';
UPDATE regions SET name = 'Area PF Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pf';
UPDATE regions SET name = 'Area PFcm (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pfcm';
UPDATE regions SET name = 'Area PFm Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pfm';
UPDATE regions SET name = 'Area PF Opercular (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pfop';
UPDATE regions SET name = 'Area PFt (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pft';
UPDATE regions SET name = 'Area PGi (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pgi';
UPDATE regions SET name = 'Area PGp (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pgp';
UPDATE regions SET name = 'Area PGs (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pgs';
UPDATE regions SET name = 'Area PH (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ph';
UPDATE regions SET name = 'ParaHippocampal Area 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pha1';
UPDATE regions SET name = 'ParaHippocampal Area 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pha2';
UPDATE regions SET name = 'ParaHippocampal Area 3 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pha3';
UPDATE regions SET name = 'Area PHT (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pht';
UPDATE regions SET name = 'Para-Insular Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pi';
UPDATE regions SET name = 'Pirform Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pir';
UPDATE regions SET name = 'Posterior InferoTemporal complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pit';
UPDATE regions SET name = 'Posterior OFC Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pofc';
UPDATE regions SET name = 'Area Posterior Insular 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_poi1';
UPDATE regions SET name = 'Posterior Insular Area 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_poi2';
UPDATE regions SET name = 'Parieto-Occipital Sulcus Area 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pos1';
UPDATE regions SET name = 'Parieto-Occipital Sulcus Area 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pos2';
UPDATE regions SET name = 'PreSubiculum (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pres';
UPDATE regions SET name = 'ProStriate Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_pros';
UPDATE regions SET name = 'PeriSylvian Language Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_psl';
UPDATE regions SET name = 'RetroInsular Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ri';
UPDATE regions SET name = 'RetroSplenial Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_rsc';
UPDATE regions SET name = 'Area s32 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_s32';
UPDATE regions SET name = 'Superior 6-8 Transitional Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_s6-8';
UPDATE regions SET name = 'Supplementary and Cingulate Eye Field (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_scef';
UPDATE regions SET name = 'Superior Frontal Language Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_sfl';
UPDATE regions SET name = 'Area STGa (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_stga';
UPDATE regions SET name = 'Area STSd anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_stsda';
UPDATE regions SET name = 'Area STSd posterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_stsdp';
UPDATE regions SET name = 'Area STSv anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_stsva';
UPDATE regions SET name = 'Area STSv posterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_stsvp';
UPDATE regions SET name = 'Superior Temporal Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_stv';
UPDATE regions SET name = 'Area TA2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_ta2';
UPDATE regions SET name = 'Area TE1 anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_te1a';
UPDATE regions SET name = 'Area TE1 Middle (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_te1m';
UPDATE regions SET name = 'Area TE1 posterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_te1p';
UPDATE regions SET name = 'Area TE2 anterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_te2a';
UPDATE regions SET name = 'Area TE2 posterior (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_te2p';
UPDATE regions SET name = 'Area TF (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_tf';
UPDATE regions SET name = 'Area TG dorsal (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_tgd';
UPDATE regions SET name = 'Area TG Ventral (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_tgv';
UPDATE regions SET name = 'Area TemporoParietoOccipital Junction 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_tpoj1';
UPDATE regions SET name = 'Area TemporoParietoOccipital Junction 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_tpoj2';
UPDATE regions SET name = 'Area TemporoParietoOccipital Junction 3 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_tpoj3';
UPDATE regions SET name = 'Primary Visual Cortex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v1';
UPDATE regions SET name = 'Second Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v2';
UPDATE regions SET name = 'Area ventral 23 a+b (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v23ab';
UPDATE regions SET name = 'Third Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v3';
UPDATE regions SET name = 'Area V3A (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v3a';
UPDATE regions SET name = 'Area V3B (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v3b';
UPDATE regions SET name = 'Area V3CD (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v3cd';
UPDATE regions SET name = 'Fourth Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v4';
UPDATE regions SET name = 'Area V4t (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v4t';
UPDATE regions SET name = 'Sixth Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v6';
UPDATE regions SET name = 'Area V6A (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v6a';
UPDATE regions SET name = 'Seventh Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v7';
UPDATE regions SET name = 'Eighth Visual Area (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_v8';
UPDATE regions SET name = 'Ventral IntraParietal Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_vip';
UPDATE regions SET name = 'VentroMedial Visual Area 1 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_vmv1';
UPDATE regions SET name = 'VentroMedial Visual Area 2 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_vmv2';
UPDATE regions SET name = 'VentroMedial Visual Area 3 (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_vmv3';
UPDATE regions SET name = 'Ventral Visual Complex (hemisferio izquierdo)' WHERE id = 'region.human.hcp-mmp1.l_vvc';
UPDATE regions SET name = 'Area 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_1';
UPDATE regions SET name = 'Area 10d (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_10d';
UPDATE regions SET name = 'Polar 10p (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_10pp';
UPDATE regions SET name = 'Area 10r (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_10r';
UPDATE regions SET name = 'Area 10v (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_10v';
UPDATE regions SET name = 'Area 11l (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_11l';
UPDATE regions SET name = 'Area 13l (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_13l';
UPDATE regions SET name = 'Area 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_2';
UPDATE regions SET name = 'Area 23c (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_23c';
UPDATE regions SET name = 'Area 23d (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_23d';
UPDATE regions SET name = 'Dorsal Area 24d (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_24dd';
UPDATE regions SET name = 'Ventral Area 24d (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_24dv';
UPDATE regions SET name = 'Area 25 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_25';
UPDATE regions SET name = 'Area 31a (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_31a';
UPDATE regions SET name = 'Area 31pd (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_31pd';
UPDATE regions SET name = 'Area 31p ventral (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_31pv';
UPDATE regions SET name = 'Area 33 prime (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_33pr';
UPDATE regions SET name = 'Area 3a (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_3a';
UPDATE regions SET name = 'Primary Sensory Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_3b';
UPDATE regions SET name = 'Primary Motor Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_4';
UPDATE regions SET name = 'Area 43 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_43';
UPDATE regions SET name = 'Area 44 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_44';
UPDATE regions SET name = 'Area 45 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_45';
UPDATE regions SET name = 'Area 46 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_46';
UPDATE regions SET name = 'Area 47l (47 lateral) (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_47l';
UPDATE regions SET name = 'Area 47m (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_47m';
UPDATE regions SET name = 'Area 47s (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_47s';
UPDATE regions SET name = 'Area 52 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_52';
UPDATE regions SET name = 'Area 55b (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_55b';
UPDATE regions SET name = 'Area 5L (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_5l';
UPDATE regions SET name = 'Area 5m (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_5m';
UPDATE regions SET name = 'Area 5m ventral (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_5mv';
UPDATE regions SET name = 'Area 6 anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_6a';
UPDATE regions SET name = 'Dorsal area 6 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_6d';
UPDATE regions SET name = 'Area 6m anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_6ma';
UPDATE regions SET name = 'Area 6mp (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_6mp';
UPDATE regions SET name = 'Rostral Area 6 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_6r';
UPDATE regions SET name = 'Ventral Area 6 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_6v';
UPDATE regions SET name = 'Lateral Area 7A (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_7al';
UPDATE regions SET name = 'Medial Area 7A (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_7am';
UPDATE regions SET name = 'Area 7m (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_7m';
UPDATE regions SET name = 'Area 7PC (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_7pc';
UPDATE regions SET name = 'Lateral Area 7P (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_7pl';
UPDATE regions SET name = 'Medial Area 7P (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_7pm';
UPDATE regions SET name = 'Area 8Ad (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_8ad';
UPDATE regions SET name = 'Area 8Av (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_8av';
UPDATE regions SET name = 'Area 8B Lateral (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_8bl';
UPDATE regions SET name = 'Area 8BM (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_8bm';
UPDATE regions SET name = 'Area 8C (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_8c';
UPDATE regions SET name = 'Area 9-46d (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_9-46d';
UPDATE regions SET name = 'Area 9 anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_9a';
UPDATE regions SET name = 'Area 9 Middle (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_9m';
UPDATE regions SET name = 'Area 9 Posterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_9p';
UPDATE regions SET name = 'Primary Auditory Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a1';
UPDATE regions SET name = 'Area anterior 10p (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a10p';
UPDATE regions SET name = 'Area a24 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a24';
UPDATE regions SET name = 'Anterior 24 prime (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a24pr';
UPDATE regions SET name = 'Area anterior 32 prime (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a32pr';
UPDATE regions SET name = 'Auditory 4 Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a4';
UPDATE regions SET name = 'Area anterior 47r (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a47r';
UPDATE regions SET name = 'Auditory 5 Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a5';
UPDATE regions SET name = 'Area anterior 9-46v (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_a9-46v';
UPDATE regions SET name = 'Anterior Agranular Insula Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_aaic';
UPDATE regions SET name = 'Anterior IntraParietal Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_aip';
UPDATE regions SET name = 'Anterior Ventral Insular Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_avi';
UPDATE regions SET name = 'Area dorsal 23 a+b (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_d23ab';
UPDATE regions SET name = 'Area dorsal 32 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_d32';
UPDATE regions SET name = 'Dorsal Transitional Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_dvt';
UPDATE regions SET name = 'Entorhinal Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ec';
UPDATE regions SET name = 'Frontal Eye Fields (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fef';
UPDATE regions SET name = 'Fusiform Face Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ffc';
UPDATE regions SET name = 'Frontal Opercular Area 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fop1';
UPDATE regions SET name = 'Frontal Opercular Area 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fop2';
UPDATE regions SET name = 'Frontal Opercular Area 3 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fop3';
UPDATE regions SET name = 'Frontal Opercular Area 4 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fop4';
UPDATE regions SET name = 'Area Frontal Opercular 5 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fop5';
UPDATE regions SET name = 'Area FST (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_fst';
UPDATE regions SET name = 'Hippocampus (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_h';
UPDATE regions SET name = 'Inferior 6-8 Transitional Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_i6-8';
UPDATE regions SET name = 'Area IFJa (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ifja';
UPDATE regions SET name = 'Area IFJp (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ifjp';
UPDATE regions SET name = 'Area IFSa (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ifsa';
UPDATE regions SET name = 'Area IFSp (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ifsp';
UPDATE regions SET name = 'Insular Granular Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ig';
UPDATE regions SET name = 'Area IntraParietal 0 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ip0';
UPDATE regions SET name = 'Area IntraParietal 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ip1';
UPDATE regions SET name = 'Area IntraParietal 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ip2';
UPDATE regions SET name = 'IntraParietal Sulcus Area 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ips1';
UPDATE regions SET name = 'Lateral Belt Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_lbelt';
UPDATE regions SET name = 'Area Lateral IntraParietal dorsal (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_lipd';
UPDATE regions SET name = 'Area Lateral IntraParietal ventral (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_lipv';
UPDATE regions SET name = 'Area Lateral Occipital 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_lo1';
UPDATE regions SET name = 'Area Lateral Occipital 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_lo2';
UPDATE regions SET name = 'Area Lateral Occipital 3 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_lo3';
UPDATE regions SET name = 'Medial Belt Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_mbelt';
UPDATE regions SET name = 'Middle Insular Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_mi';
UPDATE regions SET name = 'Medial IntraParietal Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_mip';
UPDATE regions SET name = 'Medial Superior Temporal Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_mst';
UPDATE regions SET name = 'Middle Temporal Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_mt';
UPDATE regions SET name = 'Orbital Frontal Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ofc';
UPDATE regions SET name = 'Area OP1-SII (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_op1';
UPDATE regions SET name = 'Area OP2-3-VS (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_op2-3';
UPDATE regions SET name = 'Area OP4-PV (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_op4';
UPDATE regions SET name = 'Area posterior 10p (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p10p';
UPDATE regions SET name = 'Area posterior 24 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p24';
UPDATE regions SET name = 'Area Posterior 24 prime (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p24pr';
UPDATE regions SET name = 'Area p32 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p32';
UPDATE regions SET name = 'Area p32 prime (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p32pr';
UPDATE regions SET name = 'Area posterior 47r (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p47r';
UPDATE regions SET name = 'Area posterior 9-46v (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_p9-46v';
UPDATE regions SET name = 'ParaBelt Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pbelt';
UPDATE regions SET name = 'PreCuneus Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pcv';
UPDATE regions SET name = 'Perirhinal Ectorhinal Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_peec';
UPDATE regions SET name = 'Premotor Eye Field (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pef';
UPDATE regions SET name = 'Area PF Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pf';
UPDATE regions SET name = 'Area PFcm (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pfcm';
UPDATE regions SET name = 'Area PFm Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pfm';
UPDATE regions SET name = 'Area PF Opercular (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pfop';
UPDATE regions SET name = 'Area PFt (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pft';
UPDATE regions SET name = 'Area PGi (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pgi';
UPDATE regions SET name = 'Area PGp (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pgp';
UPDATE regions SET name = 'Area PGs (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pgs';
UPDATE regions SET name = 'Area PH (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ph';
UPDATE regions SET name = 'ParaHippocampal Area 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pha1';
UPDATE regions SET name = 'ParaHippocampal Area 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pha2';
UPDATE regions SET name = 'ParaHippocampal Area 3 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pha3';
UPDATE regions SET name = 'Area PHT (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pht';
UPDATE regions SET name = 'Para-Insular Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pi';
UPDATE regions SET name = 'Pirform Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pir';
UPDATE regions SET name = 'Posterior InferoTemporal complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pit';
UPDATE regions SET name = 'Posterior OFC Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pofc';
UPDATE regions SET name = 'Area Posterior Insular 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_poi1';
UPDATE regions SET name = 'Posterior Insular Area 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_poi2';
UPDATE regions SET name = 'Parieto-Occipital Sulcus Area 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pos1';
UPDATE regions SET name = 'Parieto-Occipital Sulcus Area 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pos2';
UPDATE regions SET name = 'PreSubiculum (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pres';
UPDATE regions SET name = 'ProStriate Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_pros';
UPDATE regions SET name = 'PeriSylvian Language Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_psl';
UPDATE regions SET name = 'RetroInsular Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ri';
UPDATE regions SET name = 'RetroSplenial Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_rsc';
UPDATE regions SET name = 'Area s32 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_s32';
UPDATE regions SET name = 'Superior 6-8 Transitional Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_s6-8';
UPDATE regions SET name = 'Supplementary and Cingulate Eye Field (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_scef';
UPDATE regions SET name = 'Superior Frontal Language Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_sfl';
UPDATE regions SET name = 'Area STGa (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_stga';
UPDATE regions SET name = 'Area STSd anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_stsda';
UPDATE regions SET name = 'Area STSd posterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_stsdp';
UPDATE regions SET name = 'Area STSv anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_stsva';
UPDATE regions SET name = 'Area STSv posterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_stsvp';
UPDATE regions SET name = 'Superior Temporal Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_stv';
UPDATE regions SET name = 'Area TA2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_ta2';
UPDATE regions SET name = 'Area TE1 anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_te1a';
UPDATE regions SET name = 'Area TE1 Middle (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_te1m';
UPDATE regions SET name = 'Area TE1 posterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_te1p';
UPDATE regions SET name = 'Area TE2 anterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_te2a';
UPDATE regions SET name = 'Area TE2 posterior (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_te2p';
UPDATE regions SET name = 'Area TF (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_tf';
UPDATE regions SET name = 'Area TG dorsal (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_tgd';
UPDATE regions SET name = 'Area TG Ventral (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_tgv';
UPDATE regions SET name = 'Area TemporoParietoOccipital Junction 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_tpoj1';
UPDATE regions SET name = 'Area TemporoParietoOccipital Junction 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_tpoj2';
UPDATE regions SET name = 'Area TemporoParietoOccipital Junction 3 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_tpoj3';
UPDATE regions SET name = 'Primary Visual Cortex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v1';
UPDATE regions SET name = 'Second Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v2';
UPDATE regions SET name = 'Area ventral 23 a+b (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v23ab';
UPDATE regions SET name = 'Third Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v3';
UPDATE regions SET name = 'Area V3A (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v3a';
UPDATE regions SET name = 'Area V3B (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v3b';
UPDATE regions SET name = 'Area V3CD (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v3cd';
UPDATE regions SET name = 'Fourth Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v4';
UPDATE regions SET name = 'Area V4t (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v4t';
UPDATE regions SET name = 'Sixth Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v6';
UPDATE regions SET name = 'Area V6A (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v6a';
UPDATE regions SET name = 'Seventh Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v7';
UPDATE regions SET name = 'Eighth Visual Area (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_v8';
UPDATE regions SET name = 'Ventral IntraParietal Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_vip';
UPDATE regions SET name = 'VentroMedial Visual Area 1 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_vmv1';
UPDATE regions SET name = 'VentroMedial Visual Area 2 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_vmv2';
UPDATE regions SET name = 'VentroMedial Visual Area 3 (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_vmv3';
UPDATE regions SET name = 'Ventral Visual Complex (hemisferio derecho)' WHERE id = 'region.human.hcp-mmp1.r_vvc';
